### ISSUE TITLE
AWS Lambda + Container issue with model loading as /home is read only

### ISSUE THREAD

**Issue by dsivakumar** [dmmiller612/bert-extractive-summarizer#134]
Posted a issue here https://github.com/UKPLab/sentence-transformers/issues/923#issuecomment-1142298361
But it would be good if we have an option to pass on the cache_folder in the following initialization

https://github.com/dmmiller612/bert-extractive-summarizer/blob/84f27333aef33629444589c24933b76448777d4f/summarizer/transformer_embeddings/sbert_embedding.py#L17
self.sbert_model = SentenceTransformer(model) 

Say, I can set cache_folder=/var/task (not sure this works on aws!)

logs
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/app.py", line 10, in <module>
    model =  SBertSummarizer('paraphrase-MiniLM-L6-v2')
  File "/var/task/summarizer/sbert.py", line 26, in __init__
    model_func = SBertEmbedding(model)
  File "/var/task/summarizer/transformer_embeddings/sbert_embedding.py", line 17, in __init__
    self.sbert_model = SentenceTransformer(model)
  File "/var/task/sentence_transformers/SentenceTransformer.py", line 86, in __init__
    snapshot_download(model_name_or_path,
  File "/var/task/sentence_transformers/util.py", line 456, in snapshot_download
    os.makedirs(nested_dirname, exist_ok=True)
  File "/var/lang/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/var/lang/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)

**Comment by dsivakumar** [comment]
Resolved by setting in aws Lambda configuration->Environment variables  HOME to /tmp !! All works fine!!!
