### ISSUE TITLE
ValueError: module functions cannot set METH_CLASS or METH_STATIC

### ISSUE THREAD

**Issue by QuantumPhysicsgit** [dmmiller612/bert-extractive-summarizer#3]
I am using it on windows. 
Just by running the import line I get the following error:

'
>>>from summarizer import SingleModel
Traceback (most recent call last):

  File "<ipython-input-3-dafc92e0dffc>", line 1, in <module>
    from summarizer import SingleModel

  File "C:\Users\himansh\Anaconda3\lib\site-packages\summarizer\__init__.py", line 1, in <module>
    from summarizer.model_processors import SingleModel

  File "C:\Users\himansh\Anaconda3\lib\site-packages\summarizer\model_processors.py", line 1, in <module>
    from summarizer.BertParent import BertParent

  File "C:\Users\himansh\Anaconda3\lib\site-packages\summarizer\BertParent.py", line 1, in <module>
    from pytorch_pretrained_bert import BertTokenizer, BertModel, GPT2Model, GPT2Tokenizer

  File "C:\Users\himansh\Anaconda3\lib\site-packages\pytorch_pretrained_bert\__init__.py", line 4, in <module>
    from .tokenization_transfo_xl import (TransfoXLTokenizer, TransfoXLCorpus)

  File "C:\Users\himansh\Anaconda3\lib\site-packages\pytorch_pretrained_bert\tokenization_transfo_xl.py", line 30, in <module>
    import torch

  File "C:\Users\himansh\Anaconda3\lib\site-packages\torch\__init__.py", line 79, in <module>
    from torch._C import *

ValueError: module functions cannot set METH_CLASS or METH_STATIC
'

**Comment by dmmiller612** [comment]
It looks like it is probably an issue with the Pytorch-bert library we use. We just provide a wrapper around that library for the Bert modeling.
