### ISSUE TITLE
i have a problem when importing summarizer ---""""from summarizer import Summarizer"""

### ISSUE THREAD

**Issue by KevinLion15** [dmmiller612/bert-extractive-summarizer#92]
this is the message they give me
 None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "C:/Users/klion/AppData/Local/Programs/Python/Python39/test.py", line 1, in <module>
    from summarizer import Summarizer
  File "C:\Users\klion\AppData\Local\Programs\Python\Python39\lib\site-packages\summarizer\__init__.py", line 1, in <module>
    from summarizer.model_processors import Summarizer, TransformerSummarizer
  File "C:\Users\klion\AppData\Local\Programs\Python\Python39\lib\site-packages\summarizer\model_processors.py", line 6, in <module>
    from summarizer.bert_parent import BertParent
  File "C:\Users\klion\AppData\Local\Programs\Python\Python39\lib\site-packages\summarizer\bert_parent.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by KevinLion15** [comment]
Hello can you help  me please

**Comment by Ayush1702** [comment]
`pip install torchvision --user` 
should help

**Comment by dmmiller612** [comment]
If you are having any other issues, feel free to re-open.

**Comment by adarshcode28** [comment]
Traceback (most recent call last):
  File "d:\btech\3-YEAR\sem-6\NLP\project\extractive\bert-extractive-summarizer-master\examples\summarize.py", line 1, in <module>
    from summarizer import Summarizer
ImportError: cannot import name 'Summarizer' from 'summarizer' (unknown 
location)

**Comment by adarshcode28** [comment]
please need help

**Comment by kuluu6** [comment]
> 

pip install summarizer
